# Generated by Django 5.2.9 on 2026-01-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('family', 'Family (Care Seeker)'), ('caregiver', 'Caregiver'), ('admin', 'Admin')], default='family', max_length=20),
        ),
    ]
