# Generated by Django 5.2.9 on 2026-01-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('careseeker', 'Care Seeker'), ('caregiver', 'Caregiver'), ('admin', 'Admin')], default='careseeker', max_length=20),
        ),
    ]
