# Generated by Django 5.2.9 on 2026-01-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='verification/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='service_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
