# Generated by Django 5.2.3 on 2026-01-03 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_bio_userprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_status',
        ),
        migrations.CreateModel(
            name='CaregiverVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_document', models.FileField(upload_to='verification/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
