# Generated by Django 5.2.3 on 2026-01-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_id_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiververification',
            name='citizenship_document',
        ),
        migrations.AddField(
            model_name='caregiververification',
            name='citizenship_back',
            field=models.ImageField(blank=True, null=True, upload_to='verification/citizenship/'),
        ),
        migrations.AddField(
            model_name='caregiververification',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='verification/citizenship/'),
        ),
        migrations.AddField(
            model_name='caregiververification',
            name='document_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='caregiververification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
