# Generated by Django 5.2.3 on 2026-01-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_caregiververification_citizenship_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaregiverVerification',
        ),
    ]
