# Generated by Django 5.2.3 on 2026-01-04 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_caregiververification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='service_types',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='years_of_experience',
        ),
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_types', models.JSONField(blank=True, default=list)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_hours', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
