# Generated by Django 5.2.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caregiverprofile",
            name="hourly_rate",
        ),
        migrations.RemoveField(
            model_name="caregiverprofile",
            name="years_of_experience",
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="training_authority",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="certification_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
