# Generated by Django 5.2.3 on 2026-02-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_caregiverprofile_training_authority_certification_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
