# Generated by Django 5.2.3 on 2026-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_caregiverprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
