# Generated by Django 5.2.9 on 2026-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
