# Generated by Django 5.2.3 on 2026-02-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional care information (optional)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact name', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='person_age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of person requiring care', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='person_name',
            field=models.CharField(blank=True, help_text='Name of person requiring care', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_types',
            field=models.JSONField(blank=True, default=list, help_text="Selected services from caregiver's profile"),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time of care', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(help_text='Start date of care'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes from the care seeker (deprecated)'),
        ),
    ]
