# Generated by Django 5.2.9 on 2026-02-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_hours',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='person_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
