# Generated by Django 5.2.3 on 2026-03-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_expired_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('paid', 'Paid'), ('completion_requested', 'Completion Requested'), ('completed', 'Completed')], default='pending', max_length=25),
        ),
    ]
