# Generated by Django 5.2.3 on 2026-04-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_add_booking_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completion_requested', 'Completion Requested'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('completed', 'Completed'), ('rejected', 'Declined'), ('expired', 'Expired')], default='pending', max_length=25),
        ),
    ]
