# Generated by Django 5.2.3 on 2026-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_count',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='For message type: number of unread messages from this sender', null=True),
        ),
    ]
