[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["cd backend && pip3 install -r requirements.txt"]

[start]
cmd = "cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"