# Generated by Django 5.2.9 on 2026-02-07 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_front', models.ImageField(blank=True, help_text='Front image of citizenship document', null=True, upload_to='verification/citizenship/')),
                ('citizenship_back', models.ImageField(blank=True, help_text='Back image of citizenship document', null=True, upload_to='verification/citizenship/')),
                ('certificate', models.ImageField(blank=True, help_text='Training/qualification certificate', null=True, upload_to='verification/certificates/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_caregivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caregiver Verification',
                'verbose_name_plural': 'Caregiver Verifications',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
